[package]
name = "qishort"
version = "0.1.0"
authors = ["Dimitris Katsavos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = "*"
libc = "*"
lazy_static = "*"
